safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    incoming_cmd_topic: "/vesc/high_level/input/navigation"
    safety_output_topic: "/vesc/low_level/input/safety"

    stop_distance: 0.5
    half_cone: 1.047
    a_max: 4.0
