safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    drive_input_topic: "/drive_input"
    drive_output_topic: "/drive"

    
    safety_angle: 0.35

    hard_stop_distance: 0.3

    ttc_threshold: 0.8
